# DOMAIN=example.com docker stack deploy -c n8n.yml n8n

version: '3.8'

services:
  n8n:
    image: n8nio/n8n:${VERSION:-0.148.0}
    entrypoint: /bin/sh
    command:
      - -c
      - |
        sleep 5
        npm i -g $${NODE_FUNCTION_ALLOW_EXTERNAL:-fs}
        tini -- /docker-entrypoint.sh n8n start
    user: root
    environment:
      - NODE_ENV=production
      - N8N_PROTOCOL=${SCHEME:-https}
      - N8N_HOST=${DOMAIN:-n8n.localhost}
      - WEBHOOK_TUNNEL_URL=${SCHEME:-https}://${DOMAIN:-n8n.localhost}/
      - VUE_APP_URL_BASE_API=${SCHEME:-https}://${DOMAIN:-n8n.localhost}/
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=mariadb
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=${MYSQL_DATABASE:-n8n}
      - DB_MYSQLDB_USER=${MYSQL_USER:-n8n}
      - DB_MYSQLDB_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${ADMIN_USERNAME:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${ADMIN_PASSWORD:-myp@ssw0rd}
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL}
    volumes:
      - ${VOLUME_PATH}n8n:/home/node/.n8n
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n-${NUMBER:-1}.rule=Host(`${DOMAIN:-n8n.localhost}`)
        - traefik.http.routers.n8n-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.n8n-${NUMBER:-1}.service=n8n-${NUMBER:-1}
        - traefik.http.routers.n8n-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.routers.n8n-${NUMBER:-1}.middlewares=n8n-${NUMBER:-1}
        - traefik.http.services.n8n-${NUMBER:-1}.loadbalancer.server.port=5678
        - traefik.http.middlewares.n8n-${NUMBER:-1}.headers.customResponseHeaders.Access-Control-Allow-Origin=*
        - traefik.http.middlewares.n8n-${NUMBER:-1}.headers.customResponseHeaders.Access-Control-Allow-Headers=Content-Type
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.5.9
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=${MYSQL_DATABASE:-n8n}
      - MYSQL_USER=${MYSQL_USER:-n8n}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    networks:
      - internal

volumes:
  n8n:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
