# DOMAIN=example.com docker stack deploy -c wikijs.yml wikijs

version: '3.8'

services:
  web:
    image: requarks/wiki:${VERSION:-2.5.278}
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS=myp@ssw0rd
      - DB_NAME=wikijs
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.wikijs-${NUMBER:-1}.rule=Host(`${DOMAIN:-wikijs.localhost}`)
        - traefik.http.routers.wikijs-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.wikijs-${NUMBER:-1}.service=wikijs-${NUMBER:-1}
        - traefik.http.routers.wikijs-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.wikijs-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=wikijs
      - POSTGRES_USER=wikijs
      - POSTGRES_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
